{
  "formatVersion": "1.1",
  "component": {
    "group": "expert.rightperception.story",
    "module": "storyattributes",
    "version": "0.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "gyo5am5t2befvotmjbuwgtiusa"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.jakewharton.retrofit",
          "module": "retrofit2-kotlin-coroutines-adapter",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.2.6"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.2.6"
          }
        }
      ],
      "files": [
        {
          "name": "storyattributes-0.5.4.aar",
          "url": "storyattributes-0.5.4.aar",
          "size": 243269,
          "sha512": "35e0b5e824d4d2cee37e9293e5ba5d22069a5c89ec0928c584d369a214f387d698743b22c1c21c2cfd56b1f923e462f12111c808abcb624b467dc18474057813",
          "sha256": "f54cefaae646efdc0eb8741c8d00b7d67fe0f17ea4d46d656f7b4e375cf25056",
          "sha1": "e88171ec2efca8fa8f7f3a84bbcce0f5b9dd8462",
          "md5": "4b4c131fd4679646654d33c43257dbc6"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "storyattributes-0.5.4.aar",
          "url": "storyattributes-0.5.4.aar",
          "size": 243269,
          "sha512": "35e0b5e824d4d2cee37e9293e5ba5d22069a5c89ec0928c584d369a214f387d698743b22c1c21c2cfd56b1f923e462f12111c808abcb624b467dc18474057813",
          "sha256": "f54cefaae646efdc0eb8741c8d00b7d67fe0f17ea4d46d656f7b4e375cf25056",
          "sha1": "e88171ec2efca8fa8f7f3a84bbcce0f5b9dd8462",
          "md5": "4b4c131fd4679646654d33c43257dbc6"
        }
      ]
    }
  ]
}
