{
  "formatVersion": "1.1",
  "component": {
    "group": "expert.rightperception.story",
    "module": "storyattributes",
    "version": "0.5.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "eki4gx4n3vckdnxfw2aacd37bi"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "storyattributes-0.5.14.aar",
          "url": "storyattributes-0.5.14.aar",
          "size": 306455,
          "sha512": "a12b3561c6d1a751314a15d4a4f4cea4cccff1ab54b3621221926dd4d00fecb458905427ce2018997ccc671c5530a220a419df86aebc4293bf5dba26e98af81a",
          "sha256": "552ee4eed9524c2edca51449f787e005c9f298ab12e74df35afb94e93dd765fc",
          "sha1": "f8fbd4a134eec9046768f532cfa026b22b866d56",
          "md5": "2b4105553697caddfeb4cb2d2d158ae8"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.jakewharton.retrofit",
          "module": "retrofit2-kotlin-coroutines-adapter",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "storyattributes-0.5.14.aar",
          "url": "storyattributes-0.5.14.aar",
          "size": 306455,
          "sha512": "a12b3561c6d1a751314a15d4a4f4cea4cccff1ab54b3621221926dd4d00fecb458905427ce2018997ccc671c5530a220a419df86aebc4293bf5dba26e98af81a",
          "sha256": "552ee4eed9524c2edca51449f787e005c9f298ab12e74df35afb94e93dd765fc",
          "sha1": "f8fbd4a134eec9046768f532cfa026b22b866d56",
          "md5": "2b4105553697caddfeb4cb2d2d158ae8"
        }
      ]
    }
  ]
}
