{
  "formatVersion": "1.1",
  "component": {
    "group": "expert.rightperception.story",
    "module": "storyattributes",
    "version": "0.5.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "eefuchym5bfwzeiwpkrv3cwqeq"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "storyattributes-0.5.12.aar",
          "url": "storyattributes-0.5.12.aar",
          "size": 298989,
          "sha512": "ac5c2087583fa14e4e30ecd282eb17fad98ff7e08bc32e99ec0e3b1d11a36c47828395cc924d2efbe33b4f925a06483a3ce9f31d0e5631a95eb69097e288b519",
          "sha256": "cfb37f0d583c1e31c0025c5a3660e3fe5b03a21c15fa1da160a201679808fa18",
          "sha1": "0698d7b2e0ccecd525f5313cb85148684bceb180",
          "md5": "f9e38987264c89d60e31f0bb10d0fd42"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.jakewharton.retrofit",
          "module": "retrofit2-kotlin-coroutines-adapter",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "storyattributes-0.5.12.aar",
          "url": "storyattributes-0.5.12.aar",
          "size": 298989,
          "sha512": "ac5c2087583fa14e4e30ecd282eb17fad98ff7e08bc32e99ec0e3b1d11a36c47828395cc924d2efbe33b4f925a06483a3ce9f31d0e5631a95eb69097e288b519",
          "sha256": "cfb37f0d583c1e31c0025c5a3660e3fe5b03a21c15fa1da160a201679808fa18",
          "sha1": "0698d7b2e0ccecd525f5313cb85148684bceb180",
          "md5": "f9e38987264c89d60e31f0bb10d0fd42"
        }
      ]
    }
  ]
}
