{
  "formatVersion": "1.1",
  "component": {
    "group": "expert.rightperception.story",
    "module": "storyattributes",
    "version": "0.5.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "e7w2mnhz75aoznzep75ygbdbee"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.jakewharton.retrofit",
          "module": "retrofit2-kotlin-coroutines-adapter",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.2.6"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.2.6"
          }
        }
      ],
      "files": [
        {
          "name": "storyattributes-0.5.5.aar",
          "url": "storyattributes-0.5.5.aar",
          "size": 243279,
          "sha512": "260157ab2f804cc463aaf2b2c00529be4a5af6254f913a2ab3ccc411bbc8054533aa7275758580304b9b31c3989c0608c2576d6e090aa75ed230b392b1ab6f86",
          "sha256": "cf5806991e826d1357e1609fbc80572d0548105d5d7f077e38a14011f9f06d65",
          "sha1": "f206e8aa813550ce2926f9f8de415205caf82333",
          "md5": "89fc930184bbf1e1b95e890cd4fd1914"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "storyattributes-0.5.5.aar",
          "url": "storyattributes-0.5.5.aar",
          "size": 243279,
          "sha512": "260157ab2f804cc463aaf2b2c00529be4a5af6254f913a2ab3ccc411bbc8054533aa7275758580304b9b31c3989c0608c2576d6e090aa75ed230b392b1ab6f86",
          "sha256": "cf5806991e826d1357e1609fbc80572d0548105d5d7f077e38a14011f9f06d65",
          "sha1": "f206e8aa813550ce2926f9f8de415205caf82333",
          "md5": "89fc930184bbf1e1b95e890cd4fd1914"
        }
      ]
    }
  ]
}
