{
  "formatVersion": "1.1",
  "component": {
    "group": "expert.rightperception.story",
    "module": "storyattributes",
    "version": "0.5.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "mpkxo5bcrbey3h655m5rqd23zq"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.jakewharton.retrofit",
          "module": "retrofit2-kotlin-coroutines-adapter",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.2.6"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.2.6"
          }
        }
      ],
      "files": [
        {
          "name": "storyattributes-0.5.6.aar",
          "url": "storyattributes-0.5.6.aar",
          "size": 242673,
          "sha512": "c6bdcfd99996456ae54a617a314bb5a2d3de0fabecd5442b348d8450d7e80f61677cf55b240adf2d6b0cfb0f28246947e64f8301b4573c9bc18c75907ece4fb4",
          "sha256": "a8cfdbe20b4f0f0e93cbcdb39b1643434762261ac89db51459d6c0b3aec3f65d",
          "sha1": "e0943d59f248716a92458e9788274c2bd490667e",
          "md5": "664867ca6f40a813a589e0e8f9fddcea"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "storyattributes-0.5.6.aar",
          "url": "storyattributes-0.5.6.aar",
          "size": 242673,
          "sha512": "c6bdcfd99996456ae54a617a314bb5a2d3de0fabecd5442b348d8450d7e80f61677cf55b240adf2d6b0cfb0f28246947e64f8301b4573c9bc18c75907ece4fb4",
          "sha256": "a8cfdbe20b4f0f0e93cbcdb39b1643434762261ac89db51459d6c0b3aec3f65d",
          "sha1": "e0943d59f248716a92458e9788274c2bd490667e",
          "md5": "664867ca6f40a813a589e0e8f9fddcea"
        }
      ]
    }
  ]
}
