{
  "formatVersion": "1.1",
  "component": {
    "group": "expert.rightperception.story",
    "module": "storyattributes",
    "version": "0.5.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "zaxqmxepjbf37oxqzsh4tuy6yq"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "storyattributes-0.5.13.aar",
          "url": "storyattributes-0.5.13.aar",
          "size": 302053,
          "sha512": "a388ad75441bac1a994cc895255d7ae8205537470d01b77649f02a8cd40afea4d645dc6a2a33fbf01873742e5f65e7042a1e54e9307c17d5ffa637b4e996f8ea",
          "sha256": "d5f84337df31d7aff84f1af7945cfab965a06290c9d096bd512cc248e0cffa2f",
          "sha1": "ddf3a9ecf71d84a6a68d8b49b0af964e814cfe6c",
          "md5": "f8ad5e9013ac0ed3321bffab09222788"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.jakewharton.retrofit",
          "module": "retrofit2-kotlin-coroutines-adapter",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "storyattributes-0.5.13.aar",
          "url": "storyattributes-0.5.13.aar",
          "size": 302053,
          "sha512": "a388ad75441bac1a994cc895255d7ae8205537470d01b77649f02a8cd40afea4d645dc6a2a33fbf01873742e5f65e7042a1e54e9307c17d5ffa637b4e996f8ea",
          "sha256": "d5f84337df31d7aff84f1af7945cfab965a06290c9d096bd512cc248e0cffa2f",
          "sha1": "ddf3a9ecf71d84a6a68d8b49b0af964e814cfe6c",
          "md5": "f8ad5e9013ac0ed3321bffab09222788"
        }
      ]
    }
  ]
}
