{
  "formatVersion": "1.1",
  "component": {
    "group": "expert.rightperception.story",
    "module": "storyattributes",
    "version": "0.5.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "cocuroew6jaxlisiinwfji4fbi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.jakewharton.retrofit",
          "module": "retrofit2-kotlin-coroutines-adapter",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.2.6"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.2.6"
          }
        }
      ],
      "files": [
        {
          "name": "storyattributes-0.5.7.aar",
          "url": "storyattributes-0.5.7.aar",
          "size": 246203,
          "sha512": "bf318f04a9fec3a0a2d6cc44315402451ff69e093f2064250b73fe22cc6bccad98f751c2d4cf038cd65eef69d7112895373185da4b12b66610110407fc1569b4",
          "sha256": "f250976e9a67b3142935583e846d970544fb3d27e0ba04b4edb22f32564ee304",
          "sha1": "06b527445f20b1e209e530b61971bd4eb34f0c17",
          "md5": "5b5959cd1fd0714509563e77f9f76deb"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "storyattributes-0.5.7.aar",
          "url": "storyattributes-0.5.7.aar",
          "size": 246203,
          "sha512": "bf318f04a9fec3a0a2d6cc44315402451ff69e093f2064250b73fe22cc6bccad98f751c2d4cf038cd65eef69d7112895373185da4b12b66610110407fc1569b4",
          "sha256": "f250976e9a67b3142935583e846d970544fb3d27e0ba04b4edb22f32564ee304",
          "sha1": "06b527445f20b1e209e530b61971bd4eb34f0c17",
          "md5": "5b5959cd1fd0714509563e77f9f76deb"
        }
      ]
    }
  ]
}
