{
  "formatVersion": "1.1",
  "component": {
    "group": "expert.rightperception.story",
    "module": "storyattributes",
    "version": "0.5.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "wy5nfc5qdvfedfzxhho2vmkpv4"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.jakewharton.retrofit",
          "module": "retrofit2-kotlin-coroutines-adapter",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.2.6"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.2.6"
          }
        }
      ],
      "files": [
        {
          "name": "storyattributes-0.5.10.aar",
          "url": "storyattributes-0.5.10.aar",
          "size": 283859,
          "sha512": "db32c3817564cb7daf898ebe6ac37600aa2b3026bbf9fec8c8e13217e5b5dee8da4e1553e9f8e3e900c7cf2d6500c2ab83932dbde9aa468d1a7151f98f919199",
          "sha256": "6bdff4105bf8de07451f772267a14af1bfb11105c03b5469ff685dbc40fe329a",
          "sha1": "db5fe76eb8e2136711e9eb244215b81bbeaa2a89",
          "md5": "914102241d626a8c8f59f9e22e88c66e"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "storyattributes-0.5.10.aar",
          "url": "storyattributes-0.5.10.aar",
          "size": 283859,
          "sha512": "db32c3817564cb7daf898ebe6ac37600aa2b3026bbf9fec8c8e13217e5b5dee8da4e1553e9f8e3e900c7cf2d6500c2ab83932dbde9aa468d1a7151f98f919199",
          "sha256": "6bdff4105bf8de07451f772267a14af1bfb11105c03b5469ff685dbc40fe329a",
          "sha1": "db5fe76eb8e2136711e9eb244215b81bbeaa2a89",
          "md5": "914102241d626a8c8f59f9e22e88c66e"
        }
      ]
    }
  ]
}
