{
  "formatVersion": "1.1",
  "component": {
    "group": "expert.rightperception.story",
    "module": "storyattributes",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "ieefesvczrgwdckhvbzhfusgiq"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.jakewharton.retrofit",
          "module": "retrofit2-kotlin-coroutines-adapter",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.2.6"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.2.6"
          }
        }
      ],
      "files": [
        {
          "name": "storyattributes-0.5.0.aar",
          "url": "storyattributes-0.5.0.aar",
          "size": 245640,
          "sha512": "f6b4a636520d9a1e31513c32fbd2f360a313a98cd8eda724d9babec6e6ddc9a763e95a696b164f13d5ecb4dc1497d2d9f5cda6718b545dae7175b188864b25f7",
          "sha256": "b8457f394038664f5bf8ea131681961d49c4992a8e78f6d01a1cd5f73ba33bd9",
          "sha1": "faecb02ec45f3c5e0cd99cfe4a02a83fe9eba338",
          "md5": "46cd909af1284043d71574b55bf2ebfc"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "storyattributes-0.5.0.aar",
          "url": "storyattributes-0.5.0.aar",
          "size": 245640,
          "sha512": "f6b4a636520d9a1e31513c32fbd2f360a313a98cd8eda724d9babec6e6ddc9a763e95a696b164f13d5ecb4dc1497d2d9f5cda6718b545dae7175b188864b25f7",
          "sha256": "b8457f394038664f5bf8ea131681961d49c4992a8e78f6d01a1cd5f73ba33bd9",
          "sha1": "faecb02ec45f3c5e0cd99cfe4a02a83fe9eba338",
          "md5": "46cd909af1284043d71574b55bf2ebfc"
        }
      ]
    }
  ]
}
