{
  "formatVersion": "1.1",
  "component": {
    "group": "expert.rightperception.story",
    "module": "storyattributes",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "ovrzpw56u5bapmtxjz7rnnchi4"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.jakewharton.retrofit",
          "module": "retrofit2-kotlin-coroutines-adapter",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.2.6"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.2.6"
          }
        }
      ],
      "files": [
        {
          "name": "storyattributes-0.5.0.aar",
          "url": "storyattributes-0.5.0.aar",
          "size": 246063,
          "sha512": "e4249173f2fd1b1eaaeba6ab4fb2cfacff2e17a4b699e14eb12d9d6ebb6f14867f5cd33f07f4c59b36e822f7bfdf636c85c63201c61dda243e82cd1ed842cb2d",
          "sha256": "08e739b13564246c0d8444718da52ad3e80eda1ddfc5b3e8b4323886a16bbea2",
          "sha1": "d33982e1f42e90e7f173be519722f848ee132836",
          "md5": "076cfd61bdcad1cd846ec5d7b10e42f5"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "storyattributes-0.5.0.aar",
          "url": "storyattributes-0.5.0.aar",
          "size": 246063,
          "sha512": "e4249173f2fd1b1eaaeba6ab4fb2cfacff2e17a4b699e14eb12d9d6ebb6f14867f5cd33f07f4c59b36e822f7bfdf636c85c63201c61dda243e82cd1ed842cb2d",
          "sha256": "08e739b13564246c0d8444718da52ad3e80eda1ddfc5b3e8b4323886a16bbea2",
          "sha1": "d33982e1f42e90e7f173be519722f848ee132836",
          "md5": "076cfd61bdcad1cd846ec5d7b10e42f5"
        }
      ]
    }
  ]
}
