{
  "formatVersion": "1.1",
  "component": {
    "group": "expert.rightperception.story",
    "module": "storyattributes",
    "version": "0.5.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "qezeuj4jy5cd5e66bqrdaozqoi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.jakewharton.retrofit",
          "module": "retrofit2-kotlin-coroutines-adapter",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.2.6"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.2.6"
          }
        }
      ],
      "files": [
        {
          "name": "storyattributes-0.5.3.aar",
          "url": "storyattributes-0.5.3.aar",
          "size": 241948,
          "sha512": "8be8352cf4e1335a3488b801fbfccfacaba7fd1facb8e90e988ddf873c5d800b9aa67fd9b6240e0ec37af1a7913d752a0b6c9ea195de00cc656250a3237d361e",
          "sha256": "5344cc8aeffc2533c2e139c54dab1713535689b50de9fde47433c2cd157a0fa9",
          "sha1": "3772bb4e15fce83ea4beefc939d78d275671919c",
          "md5": "c6abd2e6a16f9dc219cd5df8ec4492a0"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "storyattributes-0.5.3.aar",
          "url": "storyattributes-0.5.3.aar",
          "size": 241948,
          "sha512": "8be8352cf4e1335a3488b801fbfccfacaba7fd1facb8e90e988ddf873c5d800b9aa67fd9b6240e0ec37af1a7913d752a0b6c9ea195de00cc656250a3237d361e",
          "sha256": "5344cc8aeffc2533c2e139c54dab1713535689b50de9fde47433c2cd157a0fa9",
          "sha1": "3772bb4e15fce83ea4beefc939d78d275671919c",
          "md5": "c6abd2e6a16f9dc219cd5df8ec4492a0"
        }
      ]
    }
  ]
}
