{
  "formatVersion": "1.1",
  "component": {
    "group": "expert.rightperception.story",
    "module": "storyattributes",
    "version": "0.5.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gqe2k6pzg5dhtkbb2fl4l6wjh4"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "storyattributes-0.5.11.aar",
          "url": "storyattributes-0.5.11.aar",
          "size": 280518,
          "sha512": "6ce9e33f2d94bf5f7e2012fded78dd2311ce42053267bb2952637a90066771c665b0af396d3ef155f3b8c5f2a0f127463dc67f2fab14b989ef9c17f13b98172c",
          "sha256": "3d133303b3062de2591b5284b1e31c19d50c3a096aac70a50ef64177804b2084",
          "sha1": "1ceadecf6f9e995cf11c3154d9ca45d21940d63d",
          "md5": "12272c3494a9d9bf95789709c973dc5f"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.jakewharton.retrofit",
          "module": "retrofit2-kotlin-coroutines-adapter",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "storyattributes-0.5.11.aar",
          "url": "storyattributes-0.5.11.aar",
          "size": 280518,
          "sha512": "6ce9e33f2d94bf5f7e2012fded78dd2311ce42053267bb2952637a90066771c665b0af396d3ef155f3b8c5f2a0f127463dc67f2fab14b989ef9c17f13b98172c",
          "sha256": "3d133303b3062de2591b5284b1e31c19d50c3a096aac70a50ef64177804b2084",
          "sha1": "1ceadecf6f9e995cf11c3154d9ca45d21940d63d",
          "md5": "12272c3494a9d9bf95789709c973dc5f"
        }
      ]
    }
  ]
}
