{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.breffi.story",
    "module": "storycontent",
    "version": "test",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "jaoingnecfc5th42ev5mgrbeza"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.realm",
          "module": "realm-android-library",
          "version": {
            "requires": "10.3.0"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-android-kotlin-extensions",
          "version": {
            "requires": "10.3.0"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-annotations",
          "version": {
            "requires": "10.3.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "com.orhanobut",
          "module": "hawk",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "net.lingala.zip4j",
          "module": "zip4j",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.github.storyclm",
          "module": "story-iot-android",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.annimon",
          "module": "stream",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.auth0.android",
          "module": "jwtdecode",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.github.tbruyelle",
          "module": "rxpermissions",
          "version": {
            "requires": "0.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "storycontent-test.aar",
          "url": "storycontent-test.aar",
          "size": 743687,
          "sha512": "dc28e9d3fcf9b39a39dce796f1780ad027aceff8e257f278bf22dfb4e496dcb0ea3640883048ca980649ff1579918cf4e35438740eadcbdb484906f2463e7ba3",
          "sha256": "ed454113abb0db3e54e0d6311313f767ba2c0dff79afafb41a45622f51633700",
          "sha1": "527dff9af778b3a47b6f9dddebfb729860b25b31",
          "md5": "a34d53238c503709e0b8f16dfe24ed5a"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.realm",
          "module": "realm-android-library",
          "version": {
            "requires": "10.3.0"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-android-kotlin-extensions",
          "version": {
            "requires": "10.3.0"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-annotations",
          "version": {
            "requires": "10.3.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "com.orhanobut",
          "module": "hawk",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "net.lingala.zip4j",
          "module": "zip4j",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.github.storyclm",
          "module": "story-iot-android",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.annimon",
          "module": "stream",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.auth0.android",
          "module": "jwtdecode",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "storycontent-test.aar",
          "url": "storycontent-test.aar",
          "size": 743687,
          "sha512": "dc28e9d3fcf9b39a39dce796f1780ad027aceff8e257f278bf22dfb4e496dcb0ea3640883048ca980649ff1579918cf4e35438740eadcbdb484906f2463e7ba3",
          "sha256": "ed454113abb0db3e54e0d6311313f767ba2c0dff79afafb41a45622f51633700",
          "sha1": "527dff9af778b3a47b6f9dddebfb729860b25b31",
          "md5": "a34d53238c503709e0b8f16dfe24ed5a"
        }
      ]
    }
  ]
}
